/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ivy;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.Point2D;
import java.util.ArrayList;

/**
 *
 * @author arrouisa
 */
public class DrawArea extends javax.swing.JPanel {

    /**
     * Creates new form DrawArea
     */
    ArrayList<Point2D.Double> listePoint;

    public ArrayList<Point2D.Double> getListePoint() {
        return (ArrayList<Point2D.Double>) listePoint.clone();
    }

    public void setListePoint(ArrayList<Point2D.Double> listePoint) {
        this.listePoint.clear();
        this.listePoint.addAll(listePoint);
        //this.revalidate();
        this.repaint();
    }

    public DrawArea() {
        initComponents();
        listePoint = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        super.paintComponent(g);
        listePoint.forEach(point -> {
            g.setColor(Color.blue);
            g.fillOval((int) point.x, (int) point.y, 4, 4);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
